### ISSUE TITLE
Decryption failure caused one-time-key to be discarded

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/matrix-rust-sdk#1761] opened 2023-04-11 07:22 UTC
Initialy reported on iOS repo
https://github.com/vector-im/element-ios/issues/7480

**Comment by richvdh** [comment] 2024-04-26 18:35
Duplicate of https://github.com/element-hq/element-ios/issues/7480

**Closed by richvdh** 2024-04-26 18:35 UTC
