### ISSUE TITLE
Lost OTK, leading to "OneTime key already exists" error and later UTDs

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/matrix-rust-sdk#1415] opened 2023-01-27 09:46 UTC
From time to time we are getting this error on various clients.

Element R iOS shows it as a modal:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/9841565/215055401-9a9754d6-198f-46f9-81dd-f182c5369d70.png">

Most other clients (including Element Web R and Element X) just log the error without showing it to the user.

This happens ([among other reasons](https://github.com/element-hq/element-meta/issues/2406#issuecomment-2079953181)) when a client creates a one-time keypair, uploads the public part to the server, and then forgets that it has done so (eg due to unsafe concurrent access to the crypto store). The client is then unable to upload further OTKs until the forgotten one is claimed by another device; and once it *is* claimed by another device, the resultant messages will be undecryptable.

**Comment by Anderas** [comment] 2023-01-31 10:10
Root cause on iOS: `recieve_sync_changes` is not multiprocess safe, and one process may be writing new values of account to the store whilst another retains stale cache that may eventually override the store with outdated values. When this happens, `next_key_id` for one time keys is dropped to some lower value, and this then triggers duplicate OTK ids.

Steps to reproduce:
1. create two `OlmMachine`s, `foreground` and background
2. simulate few sync loops on `foreground` by
    - calling `receive_sync_changes` with `key_counts` lower than 50
    - `mark_request_as_sent` for `keysUpload` setting it back to 50
    - => as a result `foreground` will keep creating new OTKs and incrementing `next_key_id`
4. call single `receive_sync_changes` on `background`
=> result: background has just overriden account in store with `next_key_id` that is much lower than background

**Comment by Anderas** [comment] 2023-01-31 10:11
Some rageshakes
- https://github.com/matrix-org/element-ios-rageshakes/issues/22849
- https://github.com/matrix-org/element-ios-rageshakes/issues/22863
- https://github.com/matrix-org/element-ios-rageshakes/issues/22936

**Comment by Anderas** [comment] 2023-01-31 10:13
Lastly we also need a recovery method, given that OTK upload failure will wedge the machine and never mark OTKs as sent. Possible solution

1. Pretend that the upload succeeded, setting a safe default value for the uploaded one-time key count on the Account
2. Claim all your keys on the server, you don't know which one-time key has lost his private parts
3. Re-upload a new fresh set of one-time keys

**Comment by richvdh** [comment] 2023-08-22 13:07
@uhoreg [wrote](https://github.com/vector-im/customer-retainer/issues/87#issuecomment-1688121704)

> Should we use the public key as the key ID rather than a counter-based key ID? That would ensure that key IDs don't collide.

It would, but it doesn't fix the underlying problem here, which is that a client has uploaded OTKs and forgotten about them, which is pretty much a guaranteed recipe for UISIs.

**Comment by uhoreg** [comment] 2023-08-22 17:33
Agreed about needing to fix the root cause of forgetting about keys.  But once the root cause is fixed, using the public key as ID would be a way of at least moving forward.  I think the other alternatives are to tell the user that the session is FUBAR and they need to re-log-in, or to have the client claim all of its OTKs and then re-upload new ones.

**Comment by richvdh** [comment] 2023-08-22 20:51
If the root cause is fixed, then it doesn't matter what we do?

> I think the other alternatives are to tell the user that the session is FUBAR and they need to re-log-in, 

That would be preferable, IMHO. I'm just concerned that Element Android and Element iOS are unlikely to be the last applications that make the mistake of running two copies of the rust SDK at once - or indeed that a similar bug might arise in any of a million other ways. And when it does, the fact we've implemented a workaround for it is going to make it that much harder to track down.

IMHO we've been too ready to implement workarounds for crypto bugs in the past (in particular: spamming out key requests left right and centre), and doing so has made it harder to actually fix those bugs.

**Comment by marcusmueller** [comment] 2023-09-30 17:57
@richvdh following the discussion on https://github.com/vector-im/element-web/issues/26231#issuecomment-1741816275 , hm, this seems to be a hard problem, even completely ignoring the implementation aspect.  (Keeping crypto state between a server and a split-brain client consistent – yay.)

Conventional wisdom would be that anything that wants to update the next key id, whichever shape it takes, to read-modify-write, atomically. That seems to be a hard to achieve constraint in separate processes, which, as far as I understand it, element-web considers it to easier to aim for a single crypto worker instead of hoping to make matrix-rust-sdk-crypto MT-safe. That's of course a bit sad for me as user who'd really like to have multiple tabs of Element open.

As pointed out to me in the issue above, synchronization through (browser) local storage is going to be prohibitive, performance-wise. Now I'm left a bit dumbfounded: if we can't have a central lock on creation of OTKs, would the root cause ever be fixable?

**Comment by richvdh** [comment] 2023-10-02 10:18
@marcusmueller as others have already mentioned, the long-term solution in element-web is to move crypto operations into a web worker. In general, it is up to the platform code (web, android and iOS) to ensure that only one copy of the rust-sdk is used on a datastore at a time.

I'm not actually sure what work remains to be done here. AIUI the issue has been solved for now in all platforms by ensuring we only have one rust-sdk process active at a time. @BillCarsonFr @uhoreg wdyt?

**Comment by marcusmueller** [comment] 2023-10-02 11:36
@richvdh thanks for the reply! I'd personally say "solved" is a bit of a mischaracterization: it's a rust-sdk shortcoming that's been *worked around*, to the effect that end users experience significantly regressed usability. Anyways, if the sensible way, and one that is actually attainable in a finite window of time, is going for a webworker architecture: agree, then there's nothing to be done here.

**Comment by richvdh** [comment] 2023-11-21 22:05
The issue as reported no longer occurs. If anyone feels that there is more work to be done, please open a new issue.

**Comment by BillCarsonFr** [comment] 2023-11-22 09:17
https://github.com/matrix-org/element-android-rageshakes/issues/59348

Reported today on android 1.6.8-dev

**Comment by BillCarsonFr** [comment] 2023-12-13 10:05
New occurence reported on EIX https://github.com/element-hq/element-x-ios/issues/2238

**Comment by kegsay** [comment] 2024-01-08 12:43
I got this today and dug out some more information. This bug is more pernicious that originally thought because it _blocks all keys being uploaded_ rather than just the affected key.

In my case, I saw in EAX logs (v0.4.0):
 - `No unused fallback keys were found on the server, generated a new fallback key. removed_fallback_key=None`
 - A `/keys/upload` request being sent out.
 - HTTP 400 `One time key signed_curve25519:AAAAAAAAAEQ already exists. Old key:...`

This happens constantly now, so I cannot upload more OTKs, meaning I am slowly running out of OTKs which will cause UTDs eventually. It also means I can't upload my fallback key.

**Comment by richvdh** [comment] 2024-01-08 13:52
>  I am slowly running out of OTKs which will cause UTDs eventually

Well, eventually someone will claim `AAAAAAAAAEQ`, which will mean you can start uploading OTKs again. The real problem is that they will claim the `AAAAAAAAAEQ` that is on the server, rather than the `AAAAAAAAAEQ` that your client knows about... causing UTDs.

**Comment by BillCarsonFr** [comment] 2024-01-08 15:10
There is another rageshake showing this behavior
https://rageshakes.element.io/api/listing/2023-11-30/183919-DZMA5M6A/logs-0001.log.gz

But in this one we can see that there was two OlmMachine created, with the same deviceId but different keys:
```
2023-11-30T18:18:11.343073Z DEBUG matrix_sdk_crypto::machine: Created a new Olm account | crates/matrix-sdk-crypto/src/machine.rs:288 | spans: login{method="identifier and password"} > with_store{user_id="@xuanjun:matrix.org" device_id="KSBNNMTVDE" ed25519_key=yzQQLODIhkZ5v9Tku9fcvodHddLF7+os8SkyFDL1E/8 curve25519_key=y1/IrbHdpFDhdcF5fHI0QVUubNmp5EcGU9WMNL4/pAU}
```

```
2023-11-30T18:18:15.945739Z DEBUG matrix_sdk_crypto::machine: Created a new Olm account | crates/matrix-sdk-crypto/src/machine.rs:288 | spans: restore_session > restore_session > with_store{user_id="@xuanjun:matrix.org" device_id="KSBNNMTVDE" ed25519_key=VvjbqDo1DCfzvv/H8nHiiJ2P00uH7DscBWEaw8NZA+8 curve25519_key=/ecKBMJ1HSdIXfaTFduL/Y8pnO+oIxRjHMH83QUXlE8}
```

later on we can see the error:
```
2023-11-30T18:20:33.322647Z DEBUG matrix_sdk::http_client: Error while sending request: Api(Server(ClientApi(Error { status_code: 400, authenticate: None, body: Standard { kind: Unknown, message: "One time key signed_curve25519:AAAAAAAAAA0 already exists. Old key: {\"key\":\"NomqZsEfsQgkKXRYhTlqJtVXrPrtyUmwyAp1rkNz5j4\",\"signatures\":{\"@xuanjun:matrix.org\":{\"ed25519:KSBNNMTVDE\":\"xU2pC19yLgr3Cd1oz/gbadpqH3LjlqJShBROCZ5y3UFGLNReHbI1pYfTUppmwdmNMyvmkMk5585BnYvPNArODQ\"}}}; new key: {'key': 'M0oBPMrurD54JggEqCDH1uR4vH4UtoEzohnUWkwl5GA', 'signatures': {'@xuanjun:matrix.org': {'ed25519:KSBNNMTVDE': 'nUWT9sKlU8KuwsfoRBjTJhbVqvCMPRFfQrtdDm21eIhwuFnDDT9OlL9AaK6uNzUtRjUmgduddoM3cE+SKzeEDw'}}}" } })))
```

The second machine probably trying to upload keys with same ids (ids are just simple increments starting 0)

**Comment by kegsay** [comment] 2024-01-08 15:18
It would be nice if `/keys/upload` didn't reject all the keys when just one is duplicated fwiw.

**Comment by richvdh** [comment] 2024-01-08 15:38
> It would be nice if `/keys/upload` didn't reject all the keys when just one is duplicated fwiw.

Hard disagree, for the reason already explained at https://github.com/matrix-org/matrix-rust-sdk/issues/1415#issuecomment-1688915795. TL;DR: if we're not correctly persisting DB transactions, it's better we know about it than paper over it and wait for some even more subtle error to happen.

**Comment by richvdh** [comment] 2024-01-08 15:39
> There is another rageshake showing this behavior
https://rageshakes.element.io/api/listing/2023-11-30/183919-DZMA5M6A/logs-0001.log.gz

could you link to the issue for this rageshake?

**Comment by kegsay** [comment] 2024-01-08 17:07
So `AAAAAAAAAEQ` equates to key 68 looking at https://github.com/matrix-org/vodozemac/blob/main/src/types/mod.rs#L39

The error message makes it clear that the key ID was _reused_ with a different key:
```
message: "One time key signed_curve25519:AAAAAAAAAEQ already exists. 
Old key: {
    \"key\":\"UOPTwvyF3/Kcsh3ToGBCCa/PXIO/42U3VN0fvpfceGI\",
    \"signatures\":{
        \"@kegan:matrix.org\":{
            \"ed25519:GJDDXTSNAD\":\"LG0n4WLaNoEI6zX6pm5mV2OzjxFJEaJEBzQxRskvZG9BU7rFs8rShfYEhuEeYEpMtH2QZT/tMKZehrmib3DLBA\"
        }
    }
};
new key: {
    'key': 'OvKerkVcp3+p8qeaxjxM6N1L+ZyeqzvGOWTBXQeGUxs', 
    'signatures': {
        '@kegan:matrix.org': {
            'ed25519:GJDDXTSNAD': 'YHAneQMnV5vA3BZNMnetBGRP8t3wWH8CCKOdTSz8HCqZ1golF/xj4zXSQhEIeYjuu9s9Az8WCuIabD92pxaEAw'
        }
    }
}
```

Vodozemac seems to store `next_key_id u64` along with `unpublished_public_keys: BTreeMap<KeyId, Curve25519PublicKey>` in-memory. Both fields get pickled into the same struct https://github.com/matrix-org/vodozemac/blob/main/src/olm/account/one_time_keys.rs#L28

In order for a key ID to be _reused_ then afaict the following has to happen:
 - Generate N OTKs. `next_key_id = N` and `len(unpublished_public_keys) == N`.
 - Upload the OTKs. This gets a 200 OK.
 - Before the next key ID is pickled, the app is terminated.
 - On restart, the pickled struct will not have `next_key_id = N` so will generate new keys and cause duplicates.

I would be surprised if this flow can happen, because I'd expect the pickled struct to be persisted _prior to the upload request_. If so, this couldn't get out of sync because upon reload, the next key ID would be correct along with the unpublished public keys.

One thing that stood out to me looking at the code is https://github.com/matrix-org/vodozemac/blob/main/src/olm/account/one_time_keys.rs#L56C1-L58C6 - `mark_as_published` does not take a list of key IDs, instead marking everything in `unpublished_public_keys` as published. Consider:
 - Create N public keys
 - Start uploading them
 - Generate M public keys before the upload completes
 - The upload completes, `mark_as_published` is called, causing keys to exist on the client but not the server.

I don't _think_ that can cause the dupe key ID issues in this bug though.




The `next_key_id` is pickled

**Comment by BillCarsonFr** [comment] 2024-03-21 12:38
Need to check recent rageshakes to see how often it is still occuring

**Comment by BillCarsonFr** [comment] 2024-04-04 16:15
New RS https://github.com/element-hq/element-x-ios-rageshakes/issues/1656

**Comment by gnunicorn** [comment] 2024-04-08 16:24
We are also experiencing this in several reports that decrypting messages fails. We have reports for iOS (multi instance) as well as MacOS (single instance) of this problem: where we see an endless loop of trying to submit the same key that is rejected by the server eventually leading to the user not being able to decrypt messages. I can provide further logs for info upon request (but not in public).

**Comment by gnunicorn** [comment] 2024-04-12 14:48
As I was asked to provide any information I have about this: while we had seen "unable to decrypt" and also this sending message occasionally before, it seems to have a huge uptick recently with several of our users reporting this issue (I am not sure whether it is an iOS only issue, but it seems to happen there predominantly, so it can be NSE related).

So I looked at the sdk upgrades we did and from the timeline I think this problem was introduced some time since 1d6c01fb342507b917697d02392686c861cbd0a7. On a quick review (especially of the olm machine) [of the changes since](https://github.com/matrix-org/matrix-rust-sdk/compare/1d6c01fb342507b917697d02392686c861cbd0a7...main) I couldn't really see anything directly myself, but maybe this is a useful information for someone else with more in-depth knowledge about that piece of code...

**Comment by kegsay** [comment] 2024-06-04 07:39
I still see this in recent rageshakes. It's hard to know if this is due to an older version, as _every_ OTK upload request will fail until the duplicate key ID has been /claim'd by someone.

There is definitely a multiprocess bug which can cause this, see [this test](https://github.com/matrix-org/complement-crypto/blob/c602cd36172a40e7bc20c6dc4c5c68dbe38eb04c/tests/notification_test.go#L438) which can fail sometimes due to insufficient cross process protection when uploading OTKs. It's currently skipped because it doesn't always reproduce the bug, hence it is flakey.

However, I've also seen this on Element X Android, so that cannot be the only scenario where dupe OTKs can be uploaded.

**Comment by kegsay** [comment] 2024-06-07 11:30
In EXA, I see this:
```
2024-05-14T23:32:01.479257Z DEBUG matrix_sdk::http_client: Error while sending request: Api(Server(ClientApi(Error { status_code: 400, body: Standard { kind: Unknown, message: "One time key signed_curve25519:AAAAAAAAAT0 already exists. Old key: {\"key\":\"/2oabX2cZa7TUjh6ZDsQsOQI3CKW9o0rJ4WJQU0K024\...
```
followed hours later by:
```
2024-05-15T13:00:28.678130Z WARN matrix_sdk_crypto::olm::account: Failed to create a new Olm session from a pre-key message: InboundCreation(MissingOneTimeKey("curve25519:/2oabX2cZa7TUjh6ZDsQsOQI3CKW9o0rJ4WJQU0K024"))
```

confirming that OTK already exists errors are causing failed Olm sessions and hence UTDs. This particular bug report was sent on Element X/0.4.12, 2024051500; Sdk e709cca2f). At the time the keys were uploaded:
```
2024-05-14T23:32:00.935934Z DEBUG elementx:  Application version: 0.4.12 (40004120) - release / gplay | 
2024-05-14T23:32:00.936164Z DEBUG elementx:  Git SHA: 4f3a66f2 | 
2024-05-14T23:32:00.936370Z DEBUG elementx:  SDK version: SDK VERSION (TODO) | 
2024-05-14T23:32:00.936646Z DEBUG elementx:  Local time: 05-15 01:32:00.928+0200 | 
```

The OTKs were uploaded as the app started, possibly hinting at the cause?

**Comment by poljar** [comment] 2024-06-19 07:35
> In EXA, I see this:
> 
> ```
> 2024-05-14T23:32:01.479257Z DEBUG matrix_sdk::http_client: Error while sending request: Api(Server(ClientApi(Error { status_code: 400, body: Standard { kind: Unknown, message: "One time key signed_curve25519:AAAAAAAAAT0 already exists. Old key: {\"key\":\"/2oabX2cZa7TUjh6ZDsQsOQI3CKW9o0rJ4WJQU0K024\...
> ```
> 
> followed hours later by:
> 
> ```
> 2024-05-15T13:00:28.678130Z WARN matrix_sdk_crypto::olm::account: Failed to create a new Olm session from a pre-key message: InboundCreation(MissingOneTimeKey("curve25519:/2oabX2cZa7TUjh6ZDsQsOQI3CKW9o0rJ4WJQU0K024"))
> ```
> 
> confirming that OTK already exists errors are causing failed Olm sessions and hence UTDs. This particular bug report was sent on Element X/0.4.12, 2024051500; Sdk [e709cca](https://github.com/matrix-org/matrix-rust-sdk/commit/e709cca2f5207262c6ae72ef0a3df10f54470e8c)). At the time the keys were uploaded:
> 
> ```
> 2024-05-14T23:32:00.935934Z DEBUG elementx:  Application version: 0.4.12 (40004120) - release / gplay | 
> 2024-05-14T23:32:00.936164Z DEBUG elementx:  Git SHA: 4f3a66f2 | 
> 2024-05-14T23:32:00.936370Z DEBUG elementx:  SDK version: SDK VERSION (TODO) | 
> 2024-05-14T23:32:00.936646Z DEBUG elementx:  Local time: 05-15 01:32:00.928+0200 | 
> ```
> 
> The OTKs were uploaded as the app started, possibly hinting at the cause?

One possibly cause might be that EXA was as well creating multiple client instances: https://github.com/element-hq/element-x-android/pull/3050.

**Comment by poljar** [comment] 2024-06-20 08:06
And another case where EX creates multiple `Client` objects in the same process: https://github.com/element-hq/element-x-ios/pull/2944

**Comment by richvdh** [comment] 2024-06-26 09:47
Can we close this then, if it's due to applications mis-using the api (now fixed?) rather than a bug in matrix-rust-sdk?

**Comment by bnjbvr** [comment] 2024-06-26 09:49
I would say we're not quite sure it is the root cause, and what would increase confidence a lot is resolving [this issue](https://github.com/element-hq/element-internal/issues/478). But we can close this one in the meanwhile, and reopen when/if it happens later (with the same doubt that the linked issue could be the panacea fix for it).

**Comment by kegsay** [comment] 2024-07-12 15:27
Collating stats on failed `/keys/upload`:
 - EXI (Today): key 12 with `request_size="11.9 kiB"` - indicating the initial set of 50 OTKs were re-uploaded, dupe client instance?
 - EXA (Dec 2023): key 51 with `request_size="255 B"` - indicating a re-upload of a consumed key.
 - EA (Nov 2023): key 52
 - EXA (Nov 2023): key 13 with `request_size="11.9 kiB"` - indicating the initial set of 50 OTKs were re-uploaded, dupe client instance?
 - EI (Jan 2024)
 - EXI (June 2024): key 610 with `request_size="1.2 kiB"`
 - EXI (June 2024): key 1109 with `request_size="254 B" `

Meanwhile, for failed decryptions due to `Failed to create a new Olm session from a pre-key message: InboundCreation(MissingOneTimeKey`:
- EW-R (April 2024)
- EXI (June 2024)
- EW-R (July 2024)

Failed `/keys/upload` will result in `InboundCreation(MissingOneTimeKey` eventually. What's notable is that EW-R does not appears to have problems with its `/keys/upload` loop, hinting that the problem is something to do with the mobile apps. The main difference I can think of is that the mobile apps will _all_ use the sqlite store, but EW uses the indexeddb store. Could there be transactional failures here which could cause this?

**Comment by bnjbvr** [comment] 2024-07-15 08:17
Could be one of many failure modes: the apps until recently would create several `Client` instances, which is super bad — I'd expect Web would create only a single `OlmMachine`; EXI is the only one to use the crypto cross-process lock; etc.

**Comment by poljar** [comment] 2024-09-13 13:23
Another case of this, at least on Android will be due to the following:

1. Android does not use the cross-process lock, so the regenerating of a `OlmMachine` does not happen.
2. They are using the `NotificationClient`.

The `NotificationClient` seems to have a bug where it unconditionally creates a copy of the`Client` object with a in-memory state and more importantly a completely new `OlmMachine`, this `OlmMachine` will over time fork off from the original `OlmMachine` the parent `Client` object has.

The constructor for the `NotificationClient` calls `Client::notification_client()`:

https://github.com/matrix-org/matrix-rust-sdk/blob/5827bb7ab33b275835f16eacb4c0fecfa79f4a2b/crates/matrix-sdk-ui/src/notification_client.rs#L109-L122

Which in turn calls `BaseClient::clone_with_in_memory_state_store()`:

https://github.com/matrix-org/matrix-rust-sdk/blob/5827bb7ab33b275835f16eacb4c0fecfa79f4a2b/crates/matrix-sdk/src/client/mod.rs#L2207

Which creates a new `BaseClient` with the `OlmMachine` set to `None`:

https://github.com/matrix-org/matrix-rust-sdk/blob/5827bb7ab33b275835f16eacb4c0fecfa79f4a2b/crates/matrix-sdk-base/src/client.rs#L169

Later on we set the `OlmMachine` to `Some` with the `set_session_meta()` call:

https://github.com/matrix-org/matrix-rust-sdk/blob/5827bb7ab33b275835f16eacb4c0fecfa79f4a2b/crates/matrix-sdk-base/src/client.rs#L266-L267

So now the two `OlmMachine` objects exists creating duplicate one-time keys, forgetting or rolling back `Session` objects.

This is likely the biggest culprit for this issue and once we fix it we might even close it.

**Comment by kegsay** [comment] 2024-09-13 14:44
https://github.com/matrix-org/complement-crypto/pull/133 is a failing regression test for the scenario @poljar is describing. This fails with a dupe OTK upload error, as per this issue's title.

**Closed** 2024-09-16 16:27 UTC
Labels: encryption
