### ISSUE TITLE
client.account().get_display_name() fails with 401 Missing access token

### ISSUE THREAD

**Issue by haecker-felix** [matrix-org/matrix-rust-sdk#1111] opened 2022-10-14 21:23 UTC
```
let bot_display_name = self.client.account().get_display_name().await.unwrap();
```
https://github.com/haecker-felix/hebbot/blob/755535d9938b712a36b5bcc2bbad05364406fcfa/src/bot.rs#L298

Generates:

```
2022-10-14T21:13:19.470738Z TRACE sync_with_callback{sync_settings=SyncSettings { timeout: 30s, full_state: false }}:sync_with_result_callback{sync_settings=SyncSettings { timeout: 30s, full_state: false }}:sync_once{sync_settings=SyncSettings { timeout: 30s, token: "SECRET_TOKEN", full_state: false }}:handle_sync_response:send_inner{request=Request { user_id: "@twig-bot:gnome.org" } config=None homeserver=None}:send{config=None homeserver="https://gnome.modular.im/" access_token=Some("SECRET_ACCESS_TOKEN") user_id=Some("@twig-bot:gnome.org") server_versions=[V1_0, V1_1, V1_2] request_type="ruma_client_api::profile::get_display_name::v3::Request"}: matrix_sdk::http_client: Sending request
2022-10-14T21:13:19.506128Z TRACE sync_with_callback{sync_settings=SyncSettings { timeout: 30s, full_state: false }}:sync_with_result_callback{sync_settings=SyncSettings { timeout: 30s, full_state: false }}:sync_once{sync_settings=SyncSettings { timeout: 30s, token: "SECRET_TOKEN", full_state: false }}:handle_sync_response:send_inner{request=Request { user_id: "@twig-bot:gnome.org" } config=None homeserver=None}:send{config=None homeserver="https://gnome.modular.im/" access_token=Some("SECRET_ACCESS_TOKEN") user_id=Some("@twig-bot:gnome.org") server_versions=[V1_0, V1_1, V1_2] request_type="ruma_client_api::profile::get_display_name::v3::Request"}: matrix_sdk::http_client: Got response: Response { status: 401, version: HTTP/1.1, headers: {"date": "Fri, 14 Oct 2022 21:13:19 GMT", "content-type": "application/json", "transfer-encoding": "chunked", "connection": "keep-alive", "cache-control": "no-cache, no-store, must-revalidate", "access-control-allow-origin": "*", "access-control-allow-methods": "GET, HEAD, POST, PUT, DELETE, OPTIONS", "access-control-allow-headers": "X-Requested-With, Content-Type, Authorization, Date", "strict-transport-security": "max-age=15724800; includeSubDomains"}, body: b"{\"errcode\":\"M_MISSING_TOKEN\",\"error\":\"Missing access token\"}" }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Http(Api(Server(Known(ClientApi(Error { kind: MissingToken, message: "Missing access token", status_code: 401 })))))', src/bot.rs:299:79
```

( I replaced the actual token with placeholders )

The same access token works for logging in, sending messages, and for receiving timeline events.

---

Synapse 1.68.0

Affected account: @twig-bot:gnome.org / #thisweek:gnome.org

**Comment by zecakeh** [comment] 2022-10-14 21:39
That would be because this endpoint shouldn't require authentication according to the spec, but the homeserver for gnome.org enforces it.

In fractal, we use `RequestConfig::force_auth()` to solve this.

**Comment by zecakeh** [comment] 2022-10-14 21:42
This is actually a duplicate of #488.

**Comment by jplatte** [comment] 2022-10-14 21:45
Oh I thought we used `force_auth` for `get_display_name` now because of that?

**Comment by zecakeh** [comment] 2022-10-14 21:50
Looking at the other issue it seems like the only thing that was fixed is being able to set `force_auth` before getting an access token.

**Comment by haecker-felix** [comment] 2022-10-15 12:35
Using `RequestConfig::force_auth()` works. Not sure if that should be handled as "fix"?

**Comment by zecakeh** [comment] 2022-10-15 13:01
@jplatte's suggestion of always enforcing auth for the profile endpoints is probably a good thing since it's something that is in the config of Synapse.

Alternatively we could also follow [MSC2949](https://github.com/matrix-org/matrix-spec-proposals/pull/2949), ie making `force_auth` the default, since it was created mostly because of this issue.

**Closed** 2022-10-18 09:19 UTC
