### ISSUE TITLE
Local identity Pinning (Local TOFU)

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/matrix-rust-sdk#1762] opened 2023-04-11 10:34 UTC
Implement a "Local Trust On First Use" (TOFU) approach on rust-sdk.

 Each device will maintain its own list of TOFU trusted identities, without checking with other devices. 
This means that a malicious server can attempt to interfere during a new login, rather than during the first session only as per MSC3834.

```[tasklist]

### Dev tasks

- [ ] Store the currently pinned MSK for a user identity (and pin/unpin API)
- [ ] Add signaling when indentity has changed
- [ ] Support for Identity Mismatch strategy (default mode would be to pin the new identity but notify user about the change, another one would be to require user validation?)
- [ ] Update share key strategy distribution and introduce a new TOFU mode (in addition to existing distribute to verified only)
- [ ] Bindings
- [ ] Database migration
```

**Comment by richvdh** [comment] 2024-08-02 11:17
This issue was intended to be a more limited version of TOFU trust than that designed in MSC3834. Closing it in favour of 
https://github.com/element-hq/crypto-internal/issues/282, which is tracking the work we are doing as part of the "invisible crypto" project. I think most of the work in the Rust SDK is covered by https://github.com/matrix-org/matrix-rust-sdk/issues/3564 and https://github.com/matrix-org/matrix-rust-sdk/issues/3565.

**Closed by richvdh** 2024-08-02 11:17 UTC
