### ISSUE TITLE
Incorrect membership state for direct rooms

### ISSUE THREAD

**Issue by alfogrillo** [matrix-org/matrix-rust-sdk#2017] opened 2023-06-06 10:50 UTC
The `Room.membership` state and also `get_dm_room` doesn't work as expected in the following case:

1. A invites B for a direct chat
2. B declines
3. A leaves the room
4. Call `get_dm_room(B)` on A's session returns a room in an inconsistent state:
    - All the members (A, B) have correctly the `leave` membership (called the `members()` function to check that)
    - Calling `membership()` on the `Room` itself incorrectly returns the `joined` membership for A
    **Expectation**: `get_dm_room(B)` returns `nil` since no joined room exists with the user B anymore
    
**Notes**
- The sliding sync is syncing apparently correctly the membership state events under the hood
- Restarting the app doesn't fix the issue
- **Delete/Install the app again fixes the issue**

Related issue: https://github.com/vector-im/element-x-ios/issues/1001

**Comment by Johennes** [comment] 2023-06-06 11:12
@manuroe would this qualify for inclusion in https://github.com/vector-im/internal-planning/issues/443?

**Comment by Johennes** [comment] 2023-06-06 11:40
@alfogrillo is https://github.com/matrix-org/matrix-rust-sdk/issues/1834 a special case of this bug?

**Comment by andybalaam** [comment] 2023-06-13 15:03
@alfogrillo the behaviour I expect is:

* A creates a DM room with B (so state of B is Invite)
* B declines the invite (so state of B is Leave)

`get_dm_room(B)` returns `nil`
`get_room(roomid).membership()` returns Join because **A** is in the room.

Is that what you expect?

**Comment by andybalaam** [comment] 2023-06-13 15:05
And if B joined the room, I would expect:

* A creates a DM room with B and B is joined (so state of B is Join)
* B leaves the room (so state of B is Leave)

`get_dm_room(B)` returns `nil`
`get_room(roomid).membership()` returns `Join` because A is in the room.

**Comment by alfogrillo** [comment] 2023-06-14 09:33
@andybalaam 

So far we expected `get_dm_room(B)` to return the first room in the account data where A has a `Join` membership.

But maybe we can fine tune the logic depending on the membership of B:
- We definitely want the room back when `B` has the `invite` state since we don't want to create a new room on the A side. What we do in this case is showing the timeline of the room (even if B didn't join yet)
- If B has the leave membership, so far we did like the previous point. This brought some UX problems we are trying to fix [this way](https://github.com/vector-im/element-x-ios/issues/1077). A good alternative is getting `nil` for `get_dm_room(B)` like you suggest (even if A had the `Join` membership yet). Client side this means that A can now create a new fresh room with B. Personally I like it, let me check if my team is happy with it.

**Comment by alfogrillo** [comment] 2023-06-14 10:14
@andybalaam since the team prefers to implement [this](https://github.com/vector-im/element-x-ios/issues/1077), I guess we need the room back from `get_dm_room(B)` even if `B` left.
This will allow us to show the timeline and give the possibility for `A` to invite `B` again.

wdyt?

**Comment by andybalaam** [comment] 2023-06-14 11:09
>     * We definitely want the room back when `B` has the `invite` state since we don't want to create a new room on the `A` side. What we do in this case is showing the timeline of the room (even if B didn't join yet)

Ah yes, I just realised this before I read your comment. I updated my comment above (before I saw your reply, sorry!).
 
>     * If B has the leave membership, so far we did like the previous point. This brought some UX problems we are trying to fix [this way](https://github.com/vector-im/element-x-ios/issues/1077). A good alternative is getting `nil` for `get_dm_room(B)` like you suggest (even if A had the `Join` membership yet). Client side this means that `A` can now create a new fresh room with `B`. Personally I like it, let me check if my team is happy with it ...
> ... since the team prefers to implement https://github.com/vector-im/element-x-ios/issues/1077, I guess we need the room back from get_dm_room(B) even if B left. This will allow us to show the timeline and give the possibility for A to invite B again.

OK. Then if you really want to start a new room, you can leave the old one, which should allow you to create a new one.

**Comment by andybalaam** [comment] 2023-06-14 14:36
I've confirmed that our current behaviour reflects what we want, and written tests for it in https://github.com/matrix-org/matrix-rust-sdk/pull/2075

**Comment by alfogrillo** [comment] 2023-06-19 08:12
@andybalaam do you think this is still related with [this](https://github.com/matrix-org/matrix-rust-sdk/issues/2078)?

**Comment by andybalaam** [comment] 2023-06-20 10:08
> @andybalaam do you think this is still related with [this](https://github.com/matrix-org/matrix-rust-sdk/issues/2078)?

I'm going to close this one as soon as my [tests](https://github.com/matrix-org/matrix-rust-sdk/pull/2075) are merged, because we do the right thing here, but https://github.com/matrix-org/matrix-rust-sdk/issues/2078 is still open and should be fixed.

**Closed** 2023-06-20 10:37 UTC
Labels: bug
