### ISSUE TITLE
I want to see the sending state in the timeline

### ISSUE THREAD

**Issue by manuroe** [matrix-org/matrix-rust-sdk#639] opened 2022-05-04 14:27 UTC
- [ ] Local echo
 - [ ] Encrypting
 - [ ] Upload progression
 - [ ] Failure (As we do not offer retry, we will just propose cancel to the end user)

**Comment by zecakeh** [comment] 2022-05-06 08:10
Isn't this a duplicate of #635?

It seems the main difference is that this one is mentioned in an iOS issue while the other one is mentionned in an Android issue.

**Comment by jplatte** [comment] 2022-12-09 09:00
Yes, duplicate of #635.

**Closed by jplatte** 2022-12-09 09:00 UTC
Labels: Z-ElementX-Alpha, A-Timeline, A-Local echo
