### ISSUE TITLE
Local echo for uploaded files

### ISSUE THREAD

**Issue by Velin92** [matrix-org/matrix-rust-sdk#2304] opened 2023-07-19 13:51 UTC
realated to: https://github.com/vector-im/element-x-ios/issues/1288

**Comment by jplatte** [comment] 2023-07-19 14:00
Soft-blocked on https://github.com/matrix-org/synapse/pull/15503.

**Comment by bmarty** [comment] 2023-12-13 08:14
Duplicate of #1732?

**Comment by jplatte** [comment] 2023-12-13 09:52
Yup.

**Closed by jplatte** 2023-12-13 09:52 UTC
Labels: enhancement, A-File-Upload, blocked, Z-Schedule
