### ISSUE TITLE
[SlidingSync] unique room identifiers

### ISSUE THREAD

**Issue by stefanceriu** [matrix-org/matrix-rust-sdk#1977] opened 2023-05-26 10:03 UTC
Given certain sliding sync operations we can end up with multiple "invalid" rooms with the same identifier. This is a problem for SwiftUI that expects all items to be unique. We're currently trying to work around this swift side by trying to assign custom identifiers to whatever rooms are duplicated. The downside is that SwiftUI won't be able to infer differences in the room and instead just replace the whole cell.

It would be great if the new RoomList API can take this into consideration

**Comment by stefanceriu** [comment] 2023-05-26 10:36
I cannot confirm or deny that we get duplicated filled rooms. We get duplicates atm but I can't tell whether it's because we merge together 2 different lists that update at different times or because this is actually a problem. 
I'm only talking about invalid rooms here

Let's imagine the following scenario: you start off with the following room list

```
Invalid(a)
Invalid(b)
Invalid(c)
---------> Visible Range
Filled(d)
Filled(e)
---------> Visible Range
Invalid(f)
Invalid(g)
```

and let assume d and e get new messages and move to the top of the list

```
Invalid(d)
Invalid(e)
Invalid(c)
---------> Visible Range
Filled(b)
Filled(c)
---------> Visible Range
Invalid(f)
Invalid(g)
```

This is what I believe happens and you end up with duplicated IDs between a filled and invalid room.

On the other hand this might yet again be a side effect of us using 2 different lists so I'm definitiely willing to wait until we adopt the RoomList API and see if it's actually a problem

**Comment by Hywan** [comment] 2023-05-26 11:42
I don't want to set the problem on you, but it's more likely that the problem is happening on your “merge 2 lists” algorithm.

Let's see with the real `RoomList` API yeah, https://github.com/matrix-org/matrix-rust-sdk/issues/1911.

**Comment by Hywan** [comment] 2023-06-15 11:23
Ensured by #1911 (and already ensured by `SlidingSync`) since we don't do weird merges between `SlidingSyncList`. Confirmed that it was a problem on `matrix_sdk_ffi` consumers, not from the SDK itself. I'm closing the issue.

**Closed by Hywan** 2023-06-15 11:23 UTC
