### ISSUE TITLE
Leaving a DM returns the room that was left when calling get_dm_room

### ISSUE THREAD

**Issue by pixlwave** [matrix-org/matrix-rust-sdk#2300] opened 2023-07-19 11:02 UTC
This is all through the FFI. Steps to reproduce:

- Create a DM room with someone (EX code [here](https://github.com/vector-im/element-x-ios/blob/6b030172e59d8fb3307018e1a7f18c1f985515a2/ElementX/Sources/Services/Client/ClientProxy.swift#L160-L161)).
- Send some messages (probably not relevant).
- They join the room (probably not relevant).
- Leave the room (by calling `room.leave()`).
- Call `client.get_dm_room(someone)` for the same person.

The room returned is the room that was left:

https://github.com/matrix-org/matrix-rust-sdk/assets/6060466/8d4569a7-89b7-4411-81dd-0fd2cc2108fb

**Comment by poljar** [comment] 2023-08-02 09:12
This is very likely caused by the thing this `FIXME` explains:

https://github.com/matrix-org/matrix-rust-sdk/blob/0f6dd644b5dcc5377ed0a1153a581ebb62bd613b/crates/matrix-sdk-base/src/sliding_sync.rs#L309-L321

One thing to note, we do mark a room as left based on a 200 response on the `/leave` endpoint:
https://github.com/matrix-org/matrix-rust-sdk/blob/0f6dd644b5dcc5377ed0a1153a581ebb62bd613b/crates/matrix-sdk/src/room/mod.rs#L132-L133

And the method that fetches DMs does look for joined rooms only:

https://github.com/matrix-org/matrix-rust-sdk/blob/0f6dd644b5dcc5377ed0a1153a581ebb62bd613b/crates/matrix-sdk/src/encryption/mod.rs#L362-L371

Based on the above I think that the following is happening:

1. The user calls the `Room::leave()` method.
2. The room is marked as left.
3. The SS proxy gives us the updated room.
4. We incorrectly mark the room as joined again due to the FIXME part.

**Comment by Hywan** [comment] 2023-08-14 15:57
(Personal note: https://matrix.to/#/!OFQtQAEkpJQVngjhsM:matrix.org/$TdZUhRwwhw8OO5SJ1wFDeu50AdwXuNj78IXNZUMC50U?via=matrix.org&via=element.io&via=integrations.ems.host).

**Comment by Hywan** [comment] 2023-08-14 18:35
There is a duplicated event (with different `pos`) when leaving a room, https://github.com/matrix-org/sliding-sync/issues/250.

**Closed** 2023-08-17 13:33 UTC
Labels: Z-Schedule, X-Needs-Rust
